#!/usr/bin/env bash
set -e # halt on error

bundle exec jekyll build

# htmlproofer sees a bunch of stuff that will be receiving incremental fixes,
# disabled for now
##bundle exec htmlproofer ./_site --disable-external
